import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { AuthProvider } from "@/components/AuthContext";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
      
        className={`${poppins.variable} antialiased`}
      >
        <ClerkProvider
  appearance={{
    variables: {
      colorPrimary: '#e05929',
      colorBackground: '#0a0a0a',
      colorInputBackground: 'rgba(255, 255, 255, 0.04)',
      colorInputText: '#ffffff',
      colorText: '#ffffff',
      colorTextSecondary: '#a3a3a3',
      colorDanger: '#ef4444',
      borderRadius: '0.75rem',
      fontFamily: 'var(--font-poppins), sans-serif',
    },
    elements: {
      // ─── Sign In / Sign Up modals ───
      card: 'bg-black/80 backdrop-blur-xl border border-white/[0.08] shadow-2xl shadow-black/40',
      headerTitle: 'text-white text-2xl font-bold tracking-tight',
      headerSubtitle: 'text-neutral-400',
      socialButtonsBlockButton:
        'bg-white/[0.06] border border-white/[0.1] text-white hover:bg-white/[0.12] transition-all duration-200',
      socialButtonsBlockButtonText: 'text-neutral-300 font-medium',
      dividerLine: 'bg-white/[0.08]',
      dividerText: 'text-neutral-500',
      formFieldLabel: 'text-neutral-400 font-medium',
      formFieldInput:
        'bg-white/[0.04] border-white/[0.1] text-white placeholder:text-neutral-600 focus:border-[#e05929]/50 focus:ring-1 focus:ring-[#e05929]/30 transition-colors',
      formButtonPrimary:
        'bg-[#e05929] hover:bg-[#ff6b3d] text-white font-semibold shadow-lg shadow-[#e05929]/25 transition-all duration-300',
      footerActionLink: 'text-[#e05929] hover:text-[#ff7043]',
      footerActionText: 'text-neutral-500',
      identityPreviewEditButton: 'text-[#e05929] hover:text-[#ff7043]',
      formFieldAction: 'text-[#e05929] hover:text-[#ff7043]',
      otpCodeFieldInput:
        'bg-white/[0.04] border-white/[0.1] text-white focus:border-[#e05929]/50',
      alertText: 'text-neutral-300',
      formFieldWarningText: 'text-amber-400',
      tagInputContainer: 'bg-white/[0.04] border-white/[0.1]',
      selectButton: 'bg-white/[0.04] border-white/[0.1] text-white',

      // ─── UserButton popover ───
      userButtonPopoverCard:
        'bg-black/90 backdrop-blur-xl border border-white/[0.08]',
      userButtonPopoverActionButton:
        'text-neutral-300 hover:bg-white/[0.06]',
      userButtonPopoverActionButtonText: 'text-neutral-300',
      userButtonPopoverFooter: 'hidden',

      // ─── UserProfile ───
      rootBox: 'w-full',
      pageScrollBox: 'bg-transparent',
      page: 'bg-transparent',
      profilePage: 'bg-transparent',
      cardBox:
        'bg-black/80 backdrop-blur-xl border border-white/[0.08] shadow-2xl shadow-black/40 rounded-2xl overflow-hidden',
      navbar: 'bg-white/[0.02] border-r border-white/[0.06]',
      navbarButton:
        'text-neutral-400 hover:text-white hover:bg-white/[0.06] rounded-lg transition-colors',
      navbarButtonIcon: 'text-neutral-500',
      navbarButton__active:
        'text-white bg-white/[0.06] border-l-2 border-l-[#e05929]',
      profileSectionTitle:
        'text-white border-b border-white/[0.06] pb-3',
      profileSectionTitleText: 'text-sm font-semibold text-white',
      profileSectionSubtitle: 'text-neutral-500',
      profileSectionContent: 'border-none',
      profileSectionPrimaryButton:
        'text-[#e05929] hover:text-[#ff7043] transition-colors',
      accordionTriggerButton:
        'text-neutral-300 hover:bg-white/[0.04] rounded-lg transition-colors',
      accordionContent: 'border-t border-white/[0.06]',
      avatarBox:
        'ring-2 ring-[#e05929]/30 ring-offset-2 ring-offset-black rounded-full',
      avatarImageActionsUpload: 'text-[#e05929] hover:text-[#ff7043]',
      avatarImageActionsRemove: 'text-neutral-500 hover:text-red-400',
      formFieldRow: 'border-b border-white/[0.04] py-3',
      formFieldLabelRow: 'text-neutral-400',
      formFieldInputShowPasswordButton:
        'text-neutral-500 hover:text-white',
      formFieldSuccessText: 'text-emerald-400',
      formFieldErrorText: 'text-red-400',
      formFieldHintText: 'text-neutral-600',
      formButtonReset:
        'text-neutral-400 hover:text-white border border-white/[0.1] hover:border-white/[0.2] bg-transparent transition-colors',
      badge:
        'bg-[#e05929]/10 text-[#e05929] border border-[#e05929]/20',
      badgePrimary:
        'bg-[#e05929]/10 text-[#e05929] border border-[#e05929]/20',
      activeDeviceListItem:
        'border border-white/[0.06] rounded-lg bg-white/[0.02] hover:bg-white/[0.04] transition-colors',
      activeDevice: 'text-neutral-300',
      activeDeviceIcon: 'text-neutral-500',
      dangerSection:
        'border border-red-500/20 rounded-xl bg-red-500/[0.04]',
      modalBackdrop: 'bg-black/80 backdrop-blur-sm',
      modalContent: 'bg-transparent shadow-none',
      footerPages: 'hidden',
      footerPagesLink: 'hidden',
    },

    // ─── Hide Google OAuth on Sign Up only ───
    signUp: {
      elements: {
        socialButtons: 'hidden',
        dividerRow: 'hidden',
      },
    },
  }}
>
  <AuthProvider>
        <Header/>
        
        {children}
        <Footer/>
        </AuthProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
